### PR TITLE
Allow URL(s) as source in jsonschema2pojo-gradle-plugin

### LINKED ISSUE #1010: URL as source not working in latest releases
The issue https://github.com/joelittlejohn/jsonschema2pojo/pull/294 works perfect if i use the 0.4.9 version of the gradle plugin but when i try to do the same with the 1.0.1 it always throw an error saying : `Cannot convert URL 'https://midomain.com/Refund-Event.json/1.json' to a file.`. Is the new version broken or i'm missing something?

### PR DESCRIPTION
**Pull request by unkish**
Closes #1010

Seems it got broken with #748, specifically this [line](https://github.com/joelittlejohn/jsonschema2pojo/pull/748/files#diff-c3c532a54570c4fff115bf5c27c101334ebeb87e0c32a132ab38ba6bcc76cb74R47).

**Note**: users would have to explicitly invoke `clean` whenever they have URL as source and know that content behind URL has changed

### CODE REVIEW

**Comment by unkish** [comment]
In last change that succeeded I've split test into unit and integration test.
I can switch it to run only `failsafe` and disable `surefire` - would that be preferred way ?

**Comment by unkish** [comment]
@joelittlejohn adjusted `jsonschema2pojo-gradle-plugin` such that it would only execute `maven-failsafe-plugin` in `install` phase.
With these changes it should be ready (if there is nothing that I've missed)

**Comment by joelittlejohn** [comment]
Sorry @unkish I misunderstood. I didn't realise their were unit tests. I'm happy to use surefire and failsafe, reach for the appropriate kind of test.

**Comment by unkish** [comment]
@joelittlejohn no worries.

I have one concern though: it seems that at present github actions will skip integration tests in `jsonschema2pojo-gradle-plugin` as:
```yml
      - name: Verify with Maven
        run: mvn verify -B
```
will not trigger it since `verify` is prior `install` phase, and
```yml
      - name: Install latest jsonschema2pojo SNAPSHOT
        run: mvn -U -B install -DskipTests -Dmaven.javadoc.skip -Dmaven.site.skip
```
will not trigger it due `-DskipTests`

**Pull request merged**
