### PR TITLE
Add initializeCollections option to jsonschema2pojo.org UI

### LINKED ISSUE #691: Add initializeCollections configuration option to jsonschema2pojo.org UI
Joshua Bloch seems to recommend empty collection class instead of null.

https://books.google.com.my/books?id=ka2VUBqHiWkC&pg=PA201&lpg=PA201&dq=josh+bloch+empty+list+instead+of+null&source=bl&ots=yZKmOfq-V4&sig=D3Nv2o2Ixp3uF769r0nBxqS3Vek&hl=en&sa=X&redir_esc=y#v=onepage&q=josh%20bloch%20empty%20list%20instead%20of%20null&f=false

Can we have an option, instead of initializing collections class as null

    public class CreateSessionResponse {
        @SerializedName("accounts")
        @Expose
        private List<Account> accounts = null;

Can we have

    public class CreateSessionResponse {
        @SerializedName("accounts")
        @Expose
        private List<Account> accounts = Collections.emptyList();

### PR DESCRIPTION
**Pull request by thachhoang**
Fix #691.

### CODE REVIEW

**Comment by thachhoang** [comment]
Would you like to add a simple `.travis.yml` that runs `lein check` on the branch?

**Comment by joelittlejohn** [comment]
@thachhoang That would be great. Thanks!

Really nice to see changes in the UI. Were you able to run this locally and verify the change? Would you like any assistance with that? (hint: `lein ring server`)

**Comment by thachhoang** [comment]
I ran `lein run -m jsonschema2pojo.server 8000`, but `lein ring server` is much nicer to type.

I'll put up a separate pull request to enable Travis.

I'm able to start the server and toggling the checkbox does produce different output for [initializeCollectionProperties.json](https://github.com/joelittlejohn/jsonschema2pojo/blob/848bdad44859550aa2b57f6c2a6fb490c6af5b8a/jsonschema2pojo-integration-tests/src/test/resources/schema/properties/initializeCollectionProperties.json).

----

With this input:
```json
{
    "type" : "object",
    "properties" : {
        "listWithValues": {
            "type" : "array",
            "default" : [100, 200, 300]
        }
    }
}
```
The output has:
```java
@JsonProperty("listWithValues")
private List<Object> listWithValues = new ArrayList<Object>(Arrays.asList(null, null, null));
```
Is this something we should fix? We can get around it by adding `javaType`:
```json
{
    "type" : "object",
    "properties" : {
        "listWithValues": {
            "javaType" : "java.util.List<java.lang.Integer>",
            "type" : "array",
            "default" : [100, 200, 300]
        }
    }
}
```
```java
@JsonProperty("listWithValues")
private List<Integer> listWithValues = new ArrayList<Integer>(Arrays.asList(100, 200, 300));
```

**Comment by joelittlejohn** [comment]
Heroku _should_ notice new commits on the `gh-pages` branch and update the deployed app automatically.

**Comment by joelittlejohn** [comment]
You can also get around that by defining the array type in the schema (`"items"`). Without that rule, anything goes.

Your addition looks good to me at jsonschema2pojo.org :+1:

**Pull request merged**
