### PR TITLE
Getters and Setters can now be activated independently

### PR DESCRIPTION
**Pull request by lstav**
Made it possible for getters and setters to be activated independently. I am not sure that I did the dynamic setters/getters correctly, so any feedback will be appreciated. I would also like feedback on the testing.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
Thanks for submitting this PR @lstav. It looks like you have been very thorough.

One issue here is that you have removed the existing config option, and I can see why - it's not easy to make these play nicely together, particularly considering the default values. We may only be able to include this in a 1.0 release.

I wonder if we can find a way to include this but keep the `includeAccessors` option. We can even deprecate it. 

So, add getters when:

```java
isIncludeAccessors() || isIncludeGetters()
```

And add setters when:

```java
isIncludeAccessors() || isIncludeGetters()
```

This way we maintain the old behaviour but can support your new features too.

**Comment by lstav** [comment]
@joelittlejohn Sounds good, I'll add those and update the PR.

**Comment by lstav** [comment]
@joelittlejohn Just added the accessor methods again, let me know if this is what you were expecting. Also, I wasn't sure if I should put @Deprecated on the accessor methods, or if we would just add them later.

**Comment by joelittlejohn** [comment]
I think includeGetters and includeSetters should be default `false`. This way, users who are currently using includeAccessors=`false` will not have getters/setters appear in their code after this change.

**Comment by lstav** [comment]
I agree, that's a good idea, I just pushed the changes.

**Pull request merged**
