### PR TITLE
Issue 481 fix

### PR DESCRIPTION
**Pull request by dadrus**
This fix solves the #464 and #481 issues. The implementation of the fix is done entirely in the PropertyRule class.

**IMPORTANT:** It will break the so far implemented naming convention of types. Instead of deriving the typename from the name of the first using property, or file name, the type name is now always based on its name from the reference (for internal references) or the actual file name for external references. Please see also my comments on #481 for more information.

**PLEASE SEE ALSO:** _TODO_s in the implementation of the `getPropertyTypeName` function (see diff view below).

Regards,
Dimitrij

### CODE REVIEW

**Comment by dadrus** [comment]
To make it better accessible, I copy the notes/questions from the mentioned *TODO*s here. In all cases they are related to the `id` of a schema, which yet is not supported.

- The first is about the nested references to self? How to handle them: e.g: `"$ref": "#/definitions/level/sublevel/actual_element"` with type information available only on `actual_element` and `level/sublevel` used as namespaces to avoid type conflicts e.g. level could also contain an `actual_element` definition which differs from the `sublevel/actual_element`. Depending on whether a `level/sublevel` element defines a type or is just used for structuring purposes, it may be worth to generate either a java class with a nested static class or java subpackages for such cases. This rule however seems to be not applicable if our `actual_element` contains an `id`, which defines the namespace of it, thus can be mapped to a java package.
- The second is about external references, e.g. `"$ref": "my_type.json"`. The uri may by any valid URL (file, classpath, java, http, etc). The url may point to a schema with a type name already defined e.g. in the document referencing it, but with different contents. How to handle this? The usage of `id` can help to overcome this ambiguity.

What does the comunity think about it?

**Comment by ctrimble** [comment]
I really like the idea of the schema's URI being directly related to the type name.  Here are some of my thoughts on this:

1. It would definitely need to be something for `v0.5.0` or later.
2. I would really like to see a one to one relationship between schema files and Java source files.
3. Nested schemas should be rendered as nested static classes, since this would eliminate namespace conflicts when generating the types.
4. I wonder if something could be done to provide a strategy for this.  This kind of change could really cause problems for people.

**Comment by dadrus** [comment]
I've already prepared something which goes into this direction. The 3a1a96de7bf5dc6dcf2904badbb06e7cd5612e8d commit, referenced in the #481 issue includes, let's say the first drop for this. Since the JSON schema file can define multiple types, like an XML schema does, I personally see the one two one relationship between not a file, but a schema for a type definition and a Java source file. That means, that from my understanding, the id defines a namespace for a type, which corresponds to a package in Java. 

Here a basic example. Let name this file `job.json`
```.json
{
    "id": "http://test.com/2016/job.json"
    "$schema": "http://json-schema.org/schema#",
    "description": "A Job definition",
    "type": "object",
    "properties": {
        "title": { "type": "string" }
    },
    "required": ["title"]
}
```

Without an id, the corresponding Java class is generated into the *"default"* package. With the *id* present, like in the example above, the class will be generated into the *com.test._2016.job* package. In the showed case the schema file contains just one type definition - of the *job*. Let me make the example more complex and add another type to the *job.json* file:

```.json
{
    "id": "http://test.com/2016/job.json"
    "$schema": "http://json-schema.org/schema#",
    "description": "A Job definition",

    "definitions": {
        "description": {
             "type": "object",
             "properties": {
                 "title": { "type": "string" }
            }
        }
    },

    "type": "object",
    "properties": {
        "title": { "$ref": "#/definitions/description" }
    },
    "required": ["title"]
}
```

Now the schema file defines two type, and thus two schemas, one for the *job* and one for *description*. Since the *description* schema does not define its own *id*, it belongs to namespace defined by the top level *id*. You say, a nested schema, like here, should be rendered as a nested static class. Why should it be nested? It has its own name *description* and having an (indirect) *id* it has its namespace. My understanding may be wrong, but as long as a type definition is not anonymous (defined inplace as a type of a property, thus does not have a name), it can be a standalone Java type, regardless whether the type defines an enum, or a class. I see it as a design error, if a namespace (defined by an *id*) defines multiple types (json schemas) with same name. If there is a need for same type name - just give it an *id*. You do it while defining an XML schema as well, right?

That also means, that not the location (folder structure) makes the types defined in the corresponding files unique, but the *id* given for each type. The aforementioned commit implements exactly this: As long as a type is referenced using *"$ref"*, it is generated as a standalone Java type. I've tried to describe the behavior in the comments for the #481 issue.

I may miss important things, but to be honest, I encountered all those issues, I've linked to #481, and was looking for a fast solution, which would satisfy my needs. The current result is available with 3a1a96de7bf5dc6dcf2904badbb06e7cd5612e8d. I do not expect everybody to accept it is as is, but it could be a starting point, or even just a source of ideas.

**Comment by dadrus** [comment]
Maybe it becomes more obvious, if a schema file does not define a top level type. Here is modified example from http://json-schema.org/latest/json-schema-core.html (I just added the `"type": "object"`):

```.json
"schema1": {
    "id": "schema.json",
    "type": "object"
},
"schema2": {
    "id": "otherschema.json",
    "type": "object"
    "nested": {
        "id": "#bar",
        "type": "object"
    },
    "alsonested": {
        "id": "t/inner.json#a",
        "type": "object"
    }
},
"schema3": {
    "id": "some://where.else/completely#",
    "type": "object"
}
```

`schema1`, `schema2` and `schema3` all define a standalone type. Each of them should correspond to a generated Java class. You see, here the type can't be derived from the file name. The `nested` and `alsonested` should be generated as nested static classes in the class generated for `schema2`.

**Comment by ctrimble** [comment]
The only reason I suggested inner static classes is that they work like a package, for name spacing purposes, and will prevent collisions at the file system level.  Again, this is just a suggestion.

This is what I would generate for the example you gave, assuming it is in `schema.json`:

```
public class Schema {
  ...
  public static class Schema1 {
    ...
    public static class Nested { ... } 
    public static class AlsoNested { ... }
  }
  public static class Schema2 { ... }
  public static class Schema3 { ... }
}
```

That would prevent files from colliding, in the case where conflicting names are present in neighboring schemas.  Also, it seems to me that mimicking the schema structure in the java types would lead to the least amount of surprise for those using the types.

**Comment by dadrus** [comment]
That's true. This is an other approach to prevent collisions. You last sentense is also very true. Going away from java types to packages would indeed lead to a lot of surprizes for people used to the behavior of the current implementation.

BTW. The schema example above is not supported by the current implementation. At least nothing was generated given the code I have in my *schema_id_support* branch. Maybe I have broken something, which was previously possible. Anyway I've recently enabled the generation of types from such schema files, which given the mentioned above *id* support would result in the following generated output:

```.java
package schema;
public class Schema1 { ... }
```

```.java
package otherschema;
public class Schema2 { ... }
```

```.java
package else.where.completely;
public class Schema3 { ... }
```

```.java
package bar;
public class Nested { ... } 
```

```.java
package t.inner
public class AlsoNested { ... }
```

If however the above schema is changed to:

```.json
"schema1": {
    "id": "schema.json",
    "type": "object"
},
"schema2": {
    "id": "otherschema.json",
    "type": "object"
    "properties": {
        "nested": {
            "type": "object"
        },
        "alsonested": {
            "type": "object"
        }
    }
},
"schema3": {
    "id": "some://where.else/completely#",
    "type": "object"
}
```

follwing is generated:
```.java
package schema;
public class Schema1 { ... }
```

```.java
package otherschema;
public class Schema2 { 
    public static class Nested { ... }
    public static class AlsoNested { ... }
}
```

```.java
package else.where.completely;
public class Schema3 { ... }
```

The bullet point 4 from your first comment is definitely very important. Both in sense of the description of the expected behaviour for the implementation, and also to inform everybody.

I've not pushed it yet, since all my work is need driven and the plugin is in my case a tool. Because of this I've not implemented/updated unit/integration tests. If you're interested in the details I can push it with given testability limitations. 

An other thing I was looking for is the the *oneOf* support. I see a lot of discussions here (#391 is very prominent). Do you know whether somebody has already done something in this direction (I mean at least basic code)?

Regards,
Dimitrij

**Comment by dadrus** [comment]
soory, I pushed the wrong button

**Comment by ctrimble** [comment]
I would take the `oneOf` discussion over to #392 and have a look at the network graph to see what commits may be out there.

**Comment by sveba** [comment]
Is there any chance to have this fix in master soon? And also have 0.4.19 released after that :)

**Comment by joelittlejohn** [comment]
@sveba from the comments and conversation so far, I don't believe this fix is complete and ready to merge. It's unlikely that this will appear in the next release.

**Comment by kiaSso** [comment]
Hi guys, i downloaded the verion 0.4.23 and this fix doesn't appear to be there.
How can I do to get only this fix without affect the rest of the code?
Is there a planned release soon?

Many thanks

**Comment by DamageShadow** [comment]
Will it be merged anytime soon?

**Comment by PeteTh** [comment]
We too would like a fix for this

**Comment by mpern** [comment]
Any ETA on merging this?

**Comment by PeteTh** [comment]
Can we get this merged ? all seem happy with the fix, it's been over a year now.

**Comment by joelittlejohn** [comment]
This change isn't ready to merge.

It breaks compatibility for existing users of generated types in a major way and still has a number of unresolved issues that make it unsuitable for inclusion in the core.

Feel free to merge this into your own custom version.

**Pull request closed without merging**
