### PR TITLE
Android support in gradle plugin (fix issue 266)

### PR DESCRIPTION
**Pull request by ben-manes**
Previously the `java` plugin was automatically applied when configuring the task dependencies. This was not compatible with the `android` plugin. Now this plugin will inspect the build to determine the right configuration to target.

Added the example provided by @samskiter that demonstrated the bug and now shows a working sample.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
@ben-manes feel free to merge this when you're ready.

**Comment by samskiter** [comment]
Hi @ben-manes  I checkout out the repo and opened the android project up in android studio and still got the same error. I assume that's because the jsonschema2pojo dependency is still being pulled in from maven, so I'll have to trust you that this fixes it...

**Comment by ben-manes** [comment]
@samskiter, you have to perform `mvn install` first, which would make the dependency available in a local repository.

**Comment by joelittlejohn** [comment]
Thanks @ben-manes and @samskiter!

**Pull request closed without merging**
