### PR TITLE
[Issue 555] Add test for constructors + extends

### PR DESCRIPTION
**Pull request by samskiter**
PR for fix for #555 ... WIP

### CODE REVIEW

**Comment by samskiter** [comment]
I've put this in the main repository incase anyone else cares to have a go at fixing it.... it seems to be that the Schema object needs to be aware of the concept of a superclass. then we could iterate superclasses to compile the list of properties.

**Comment by samskiter** [comment]
@joelittlejohn So I'm digging around and coming up with all sorts of ideas for this and #554 
Maybe we could have a chat tonight about both?

I'm currently wondering whether doing what I proposed in 554 would help this bug at all. Related to that, I'm wondering whether `Rule.apply()` could be changed to have a different signature:

`R apply(String nodeName, T generatableType, Schema currentSchema);`

As the `node` argument could probably be made available from `currentSchema.getContent()`.

It would be really useful to talk through the architecture you have now and what you think of my proposals...

Thanks,

Sam

**Comment by ctrimble** [comment]
If you are going to be discussing the signature of Rule, I suggest that you modify it to take a single context object, possibly immutable.  This would allow the contract to be widened, as the project evolves, without too much impact on those implementing the interface.

**Comment by samskiter** [comment]
@ctrimble Yea I was coming to the same conclusion - the context can just be the existing Schema object but with some more information stored in it. I think storing the resolved JType in it as is currently done is OK so it would be mutable

**Comment by joelittlejohn** [comment]
I like the idea of a adding a context object to that signature.

Regarding naming, my main concern is that we enumerated as many edge-cases as possible, in particular those where refs and fragments paths are used.

One thing to be careful of here is biting off too much in one go. It would be good to make some small steps towards this that we can verify and merge (e.g. add the context object to make the signature more powerful) before doing anything radical around naming.

Thanks for taking an interest in these things @samskiter. I'm not likely to have time to devote to this as I've recently started a new job and have calls most evenings.

**Comment by samskiter** [comment]
Ok, plan of action is context object, then naming. As for this constructor
bug, I can't quite see the best way to fit in the information about "parent
class" and "parent class properties". I suppose both could be worked out
every time they are needed. Anything else is just an optimisation...

**Comment by samskiter** [comment]
Further question - what are the rules for adding schemas to the
schemastore? Any reason all Schema objects shouldn't be added?

**Pull request closed without merging**
