### PR TITLE
Accept url sources

### PR DESCRIPTION
**Pull request by jvasiljevich**
This PR was made to implement enhancement described in https://github.com/joelittlejohn/jsonschema2pojo/issues/293

### CODE REVIEW

**Comment by westeezy** [comment]
:+1:  This change would be very helpful to my project.

**Comment by madorb** [comment]
This change would be very helpful to MY project

**Comment by joelittlejohn** [comment]
Thanks for working on this. There's quite a few changes so I'd quite like to give this a thorough look through before merging, but in general I don't see a problem with adding this feature in the way you have.

I noticed that the integration tests are currently failing, could you take a look at this?

**Comment by jvasiljevich** [comment]
@joelittlejohn thanks for taking a look!  Regarding the test failure, it looks like it's only a single test.  Specifically, the `pathWithSpacesInTheNameDoesNotFail` test that's failing within RegressionIT.  

Oddly enough, when run from my IDE, that test also fails on master.  It does pass on master when run from the command line though...seems strange.  At any rate, I'll take a closer look at it.

**Comment by joelittlejohn** [comment]
I expect this is something to do with basedir when running in your IDE.

**Comment by jvasiljevich** [comment]
Had a chance to look at the failing test this morning.  Fixed a url decoding issue in the node naming functionality.  Tests are passing now.

**Pull request merged**
