### PR TITLE
Fix link to index.css

### PR DESCRIPTION
**Pull request by thachhoang**

### CODE REVIEW

**Comment by joelittlejohn** [comment]
@thachhoang thanks Thach!

**Comment by thachhoang** [comment]
The GitHub Pages site didn't seem to build correctly, all the resources links are currently 404, like: http://joelittlejohn.github.io/jsonschema2pojo/resources/public/lib/codemirror-compressed.js

**Comment by joelittlejohn** [comment]
Yeeeeaaah.

I've tried to re-run the built but received a timeout again. Either GitHub is applying a new timeout, or the contents of gh-pages has got large enough to hit some build timeout, or GitHub is having some issues at the moment. I'm going to do a little more research and see if I can get this to build ASAP.

**Comment by joelittlejohn** [comment]
Looks good now after another re-run. I triggered this with an empty commit like:

```
git commit --allow-empty -m "Trigger gh-pages rebuild"
```

**Pull request merged**
