### PR TITLE
#455 Override builder methods from parent class

### PR DESCRIPTION
**Pull request by blizznets**
@joelittlejohn Could you please review it.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
This looks good @blizznets. Two things to do:

1. Could you remove the javadoc reformatting? It doesn't fit with the format of the other javadoc block in this project.
2. Before we can include this feature, we _must_ have an integration test that covers it to ensure that the feature is not lost in a future version. Take a look at the existing integration tests, there are some helper classes that make them quite easy to write.

**Comment by joelittlejohn** [comment]
(Sorry, didn't mean to close that)

**Comment by blizznets** [comment]
@joelittlejohn sounds reasonable, done.
P.S. Sorry for formatting. I'd missed it somehow.

**Comment by joelittlejohn** [comment]
Thanks @blizznets! Please squash this into 1 commit and I will merge.

**Comment by blizznets** [comment]
@joelittlejohn done

**Pull request merged**
