### PR TITLE
Add Moshi 1.x annotation style

### LINKED ISSUE #523: Add Moshi to annotation styles
It would be great if you could add [Moshi](https://github.com/square/moshi) to list of _Annotation styles_ and output the POJOs accordingly.

/cc @square @JakeWharton

### PR DESCRIPTION
**Pull request by johnjohndoe**
Resolves #523.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
This looks great. 

The one comment I have is, shall we go for `MOSHI` instead of `MOSHI1` (throughout the code-base)? There may never be a Moshi 2.x, and if there is, we can add `MOSHI2`.

**Comment by johnjohndoe** [comment]
I intentionally used `MOSHI1` as being used for `JACKSON1`. I consider Moshi such as [other libraries by Square](https://github.com/square/) to be a fast moving target. Therefore, I would suggest using `MOSHI1` over `MOSHI`.

**Comment by johnjohndoe** [comment]
:+1:

**Comment by johnjohndoe** [comment]
When will Moshi be available on the [website](http://www.jsonschema2pojo.org)?

**Comment by joelittlejohn** [comment]
I don't usually add niche features to the website. Do you need it there?

**Comment by johnjohndoe** [comment]
I would not call Moshi a niche JSON library. My personal motivation to add the feature was to have it on the website.

**Comment by johnjohndoe** [comment]
I like to encourage you once again to also list Moshi on the [website](http://www.jsonschema2pojo.org).

- [Software packages which depend on moshi](https://www.versioneye.com/java/com.squareup.moshi:moshi/references)
- [GitHub projects which depend on moshi](https://github.com/search?q=compile+%27com.squareup.moshi&type=Code&utf8=%E2%9C%93)

**Comment by Mark-Mush** [comment]
Hi guys, please add it to the website :)
Moshi is better than Gson and Jackson, especially when combined with Retrofit. I wanted to use it for my project, but then discovered that the website doesn't support Moshi annotations, this is how I found your convo, many developers are switching to Moshi, it was developed by the same guys that invented Gson.

Really thankful to you, you guys are awesome!

**Comment by joelittlejohn** [comment]
Yeah, lets add it to the website. Clearly Moshi is doing well.

@Mark-Mush Did you know this project does support Moshi and you can use this feature from Maven/Gradle/etc?

**Comment by Mark-Mush** [comment]
I figured that it was possible, I'm finishing a course on Android programing so I wanted to use the best/latest technology, I wasn't quite sure how to use the jsonschema2pojo library with gradle/maven ^_^;

**Comment by joelittlejohn** [comment]
@johnjohndoe This is up on the site now :+1:

**Comment by johnjohndoe** [comment]
Awesome! :hugs: Thanks a lot. Works nicely!
Out of curiosity: Was [this](https://github.com/joelittlejohn/jsonschema2pojo/commit/baf425050fb984bc178d51d8811f4e59e4299c98) the only change needed? I did not expect such a small change.

**Comment by joelittlejohn** [comment]
Yes, that's the change. The backend parses this string to an AnnotationStyle enum using valueOf, so there's nothing more to do. 

If your familiar with Clojure, changes on the website are very easy. Just `lein ring server` to run it and test locally.

**Pull request merged**
