### PR TITLE
Fix for 725

### PR DESCRIPTION
**Pull request by michalkolodziejski**
In my project I've hit the #725 issue - while working with `machine generated` schema, that contains an empty element in `required` array.

For verification purposes I've used slightly modified schema from #725 (added nonempty element to mix up empty and nonempty ones in array).

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Silly",
    "type":"object",
    "description":"silly example",
    "required": ["", "code", ""],
    "properties": {
        "code" : {
            "type":"string",
            "description":"blah blah blah"
        }
    }
}
```

Also the schema was changed `requiredArray.json` (added empty element to `required` array) to make integration test fail when run without the change.

### CODE REVIEW

**Comment by ctrimble** [comment]
The empty string is a valid key in JSON and it can be required.

**Comment by michalkolodziejski** [comment]
@ctrimble the `required` array is for referencing fields (thus keys as You've suggested). What is the purpose of having an empty key (thus valid in JSON) for a property name, and what about duplicacy? Moreover - what would be an expected generated POJO? Empty property with an "empty name" (what about getters and setters then)?

**Comment by ctrimble** [comment]
@michalkolodziejski I don't think that we should shave off parts of the specification that we do not see as useful.  There may be some real technical limitations here, since `""` as a name is foreign to Java, but I am not sure what those are.  The schema you posted has a definition, and it should fail on:

```
{ "code": "some text" }
```

and pass for:

```
{ "code": "some text", "": null }
```

**Comment by michalkolodziejski** [comment]
@ctrimble please see OP for #725 - the real issue is `java.lang.StringIndexOutOfBoundsException: String index out of range: 0` which is raised while processing "empty" Array in`"required": [""],` which I've replaced to conform my situation with `"required": ["", "code", ""]`.

**Comment by ctrimble** [comment]
Yes, the name helper assumes that the string has at least one character.  That means this is probably also broken:

```
{
  "type": "object",
  "properties": {
    "": {
      "type": "string"
    }
  }
}
```

Generating a field and methods for that is doable, when binding annotations are used.  I am not sure how well that will work with the JSR 303 annotations.

**Comment by joelittlejohn** [comment]
Good points. If be interested just to check whether Jackson and Gson can handle this when the right annotations are present. If they can, we can certainly choose a Java name to represent this.

If it's not feasible to support this on Java due to the limitations of other libraries in the ecosystem, I'm happy to ignore the empty string in that list. We aren't a validator, this tool makes a lot of compromises to ensure that it can more often than not offer some generated output that can (at the very least) hold the data that the schema describes.

**Comment by ctrimble** [comment]
So, I just set up a quick test case and it looks like there are a lot more technical issues in here than I thought.  In particular, `@JsonProperty("")` does not mean `a property with key ""` instead it means 'use the field name without modification`.  So:

```
@JsonProperty("")
public void set( String _EMPTY_KEY_ ) {
  this._EMPTY_KEY_ = _EMPTY_KEY_;
}
```

maps to the property `"set"` instead of the property `""`.  It seems like the empty string is a non starter.

**Comment by ctrimble** [comment]
@michalkolodziejski @joelittlejohn sorry for distracting this PR.

LGTM.

**Comment by joelittlejohn** [comment]
Thanks all :+1:

**Pull request merged**
