### PR TITLE
Replace commons-lang equals, hashCode, and toString with generated code

### PR DESCRIPTION
**Pull request by ehrmann**
commons-lang is a *relatively* large library for users to include just for adding `toString()`, `equals()`, and `hashCode()`. This removes that dependency and uses generated code instead.

It avoids calls like `Objects.hash()`, `Double.hashCode()`, and `Objects.equals()` that were added in later versions of Java.

Generated code looks something like this:
```
public class ComplexTypesArray {
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(ComplexTypesArray.class.getName())
                .append('@')
                .append(Integer.toHexString(System.identityHashCode(this)))
                .append('[');
        sb.append("additionalProperties");
        sb.append('=');
        sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
        sb.append(',');
        if (sb.charAt((sb.length()- 1)) == ',') {
            sb.setCharAt((sb.length()- 1), ']');
        } else {
            sb.append(']');
        }
        return sb.toString();
    }

    @Override
    public int hashCode() {
        int result = 1;
        result = ((result* 31)+((this.additionalProperties == null)? 0 :this.additionalProperties.hashCode()));
        return result;
    }

    @Override
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        }
        if ((other instanceof ComplexTypesArray) == false) {
            return false;
        }
        ComplexTypesArray rhs = ((ComplexTypesArray) other);
        return ((this.additionalProperties == rhs.additionalProperties)||((this.additionalProperties!= null)
                && this.additionalProperties.equals(rhs.additionalProperties)));
    }
}
```

### CODE REVIEW

**Comment by ehrmann** [comment]
I wasn't able to get jsonschema2pojo-gradle-plugin to pass tests. It looks like 

`classpath 'org.jsonschema2pojo:jsonschema2pojo-gradle-plugin:latest.integration'` in `jsonschema2pojo-gradle-plugin/example/java/build.gradle` actually pulls in the latest *repository* version of `jsonschema2pojo-*` rather than the one from the project.

**Comment by joelittlejohn** [comment]
Great stuff. Thanks for this! Are you aware of any functional difference between the commons-lang implementations and the code you have generated?

**Comment by ehrmann** [comment]
I should look into in more (or add more tests). I tried to match the behavior of `toString`. `Equals` should generally do the right thing.

`HashCode` is probably different. The only time I can think of a change to `hashCode` making a difference is a serialized HashMap. Luckily, [OpenJDK's HashMap](http://hg.openjdk.java.net/jdk7/jdk7/jdk/file/9b8c96f96a0f/src/share/classes/java/util/HashMap.java#l1025) rebuilds the map on deserialization. Since this doesn't change any fields or method signatures, these classes will have the same `SerialVersionUID`.

**Comment by joelittlejohn** [comment]
Great. I don't think identical behaviour is required, here (particularly, as you say, for `hashCode`). I only ask so that we can understand any difference that may exist, and also preempt support questions.

I'll merge this for the next release.

**Comment by ehrmann** [comment]
I might add a few tests to check the string format.

**Comment by ehrmann** [comment]
I added a test class for toString as a separate commit. It looks like the output is generally compatible. The might be an edge case, but it's really close.

**Comment by ehrmann** [comment]
@joelittlejohn Any idea when you'll make the next release?

**Pull request merged**
