### PR TITLE
Add @JsonPropertyDescription when "description" property present

### PR DESCRIPTION
**Pull request by activey**
Now when "description" for field is present it will generate @JsonPropertyDescription annotation usage.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
@activey Could take a look at the changes and remove things like the SNAPSHOT version change that are not related to your PR?

**Comment by activey** [comment]
Mhm, I think I will just leave it all for 0.4.24 release, will revert it back.

**Comment by activey** [comment]
Done.

**Comment by joelittlejohn** [comment]
Note: this change requires that user choose Jackson 2.3.0 or later.

**Pull request merged**
