### PR TITLE
Enable development of context-aware rules.

### PR DESCRIPTION
**Pull request by jrehwaldt**
Add JsonNode `parent` to rules.

This is required in order to implement context-aware rules, e.g. such as gh-910.

Breaking change.

### CODE REVIEW

**Comment by jrehwaldt** [comment]
This also helps implementing gh-909 and fixing gh-906. I've also seen previous PRs neeing similar functionality (e.g. gh-622).

I am open to implement another approach if you are in favor of another solution.

**Comment by joelittlejohn** [comment]
I think you're right that it would be good to get this change added before 1.0.0 is released :+1:

**Comment by jrehwaldt** [comment]
Another refinement would be to add a general `Context` argument instead, which could then be extended further in the future. Part of this would be this parent, or maybe the whole branch (parent->parent's parent->...). Just putting it out as suggestion. Not sure if this would be better.

Something along the lines of

```
interface Context {
	JsonNode parent()
	JsonNode current()
    // extensible in future
}
```

**Comment by jrehwaldt** [comment]
Thanks for considering and merging! :)

**Pull request merged**
