### PR TITLE
Added support for custom date-time, date, time classes.

### PR DESCRIPTION
**Pull request by joelittlejohn**
Tidying up and replacing #433.

### CODE REVIEW

**Comment by joelittlejohn** [comment]
@dmiorandi I've recreated this by exporting a patch from your fork. Could you take a look through the changes and let me know if you're happy for me to merge this:

https://github.com/joelittlejohn/jsonschema2pojo/pull/469/files

?

Thanks

**Comment by dmiorandi** [comment]
Your commit seems ok. Please go on. 
Tks @joelittlejohn for you support.

A question, more or less when  you have in plan to release x.18?

**Comment by joelittlejohn** [comment]
Oh, very soon if you need it. I'm happy to do a release with just one
change if necessary.

**Comment by dmiorandi** [comment]
Ok I would like integrate .18 into raml-for-jax-rs that in under releasing in these days,
so I'm going to try merged snapshot and if it's all right I would like to ask to you a release.

**Comment by dmiorandi** [comment]
Ok merged snapshot is ok for me. I've made a manual test rebuilding my project with .18-SNAPSHOT
and works as expected.
If is possible to have a release .18 with just this feature should be great!
Tks @joelittlejohn  for your availability.

**Comment by joelittlejohn** [comment]
@dmiorandi 0.4.18 has been released, it will appear in Maven Central in a few hours.

**Comment by dmiorandi** [comment]
Great news. Tks

**Pull request merged**
